---
- name: Config Web VMs with docker
  hosts: elk
  become: true
  name: "Provision Elk Playbook"
  tasks:
  - name: Use more memory
    sysctl:
      name: vm.max_map_count
      value: '262144'
      state: present
      reload: yes

  - name:   install packages
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name:   install python3-pip
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name:   python docker module
    pip:
      name: docker
      state: present

  - name:  Downloadd sebp/elk:761
    docker_container:
      image: sebp/elk:761
      name: elk
      published_ports: "5601:5601,9200:9200,5044:5044"
      restart_policy: always
      state: started
  - name:  Enable docker service
    systemd:
      name: docker
      enabled: yes